// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DetaBaseCountext))]
    [Migration("20251114172024_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebApplication1.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryName = "Jordon",
                            ShortName = "JOR"
                        },
                        new
                        {
                            Id = 2,
                            CountryName = "Kuwait",
                            ShortName = "KUW"
                        },
                        new
                        {
                            Id = 3,
                            CountryName = "Bahrain",
                            ShortName = "BAH"
                        });
                });

            modelBuilder.Entity("WebApplication1.Data.Hotelcs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Amman",
                            CountryId = 1,
                            HotelName = "Kempinski",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kuwait City",
                            CountryId = 2,
                            HotelName = "Jumeirah",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Manama",
                            CountryId = 3,
                            HotelName = "Gulf Hotel",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("WebApplication1.Data.Hotelcs", b =>
                {
                    b.HasOne("WebApplication1.Data.Country", "CountryName")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryName");
                });
#pragma warning restore 612, 618
        }
    }
}
